version 

services:
  # Database
  db:
     image : mysql:5.7
     volume:
       - db+data:/var/lib/mysql
     restart : always
     environment :
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
     networks:
       - wpsite
  #phpmyadmin
  phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - '8080:80'
     environment: 
       PHA_HOST: db
       MYSQL_ROOT_PASSWORD: password
     network:
       - wpsite
  # wordpress
  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - '8080:80'
     restart: always
     volumes:['./:/var/www/html']
     environment:
       WORDPRESS_DB_HOST: db:3386
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
       - wpsite
networks:
  wpsite:
volumes:
  db_data:

